from modules.gameManager import GameManager, GameMode
from modules.ui import UI

def main():
    exit: bool = False
    inputs: list = [] # parsed list of player inputs?

    ui = UI()
    game_manager = GameManager()
    game_manager.start()

    ui.refresh()

    while game_manager.mode != GameMode.EXIT:
        # potential structure:
        # * print out/show current state of the game
        # * get player input
        # * generate actions for AI controlled entities
        # * process input and turn it into UI or in-game actions
        # * process actions quie and update game state
        #
        # since game is turn-based does not need a separation of UI and game state handling
        # real-time would require launching player inputs and game state handling as
        # a separte loops and clear handling of shared data

        #"""
        ui.update(game_manager) #prints/out renders current game state for current player

        inputs.extend(ui.get_player_commands())
        #inputs.extend(ai.get_inputs())

        # actions generated by AI logic are handled the same way as player actions
        # it's slower buy makes it less likely for AI to break rules unintentionally
        inputs.reverse()
        print(f"{inputs}")
        game_manager.generate_actions(inputs)
        game_manager.update()
        #"""


if __name__ == "__main__":
    main()
